DROP TABLE IF EXISTS peliculas;
CREATE TABLE peliculas
(
id_Pelicula INT GENERATED BY default as IDENTITY not null,
titulo VARCHAR(100),
director VARCHAR(100),
genero VARCHAR(50),
duracion INT,
anio INT
);
INSERT INTO peliculas (titulo, director, genero, duracion, anio)
VALUES ('El Padrino', 'Francis Ford Coppola', 'Drama', 175, 1972);

INSERT INTO peliculas (titulo, director, genero, duracion, anio)
VALUES ('Pulp Fiction', 'Quentin Tarantino', 'Crimen', 154, 1994);

INSERT INTO peliculas (titulo, director, genero, duracion, anio)
VALUES ('El Señor de los Anillos: La Comunidad del Anillo', 'Peter Jackson', 'Fantasía', 178, 2001);

INSERT INTO peliculas (titulo, director, genero, duracion, anio)
VALUES ('Interstellar', 'Christopher Nolan', 'Ciencia ficción', 169, 2014);
